apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: multi-tenancy-gitops
    group: pipeline
    type: git
  name: gitops-repo
data:
  branch: master
  host: github.com
  org: Justin-MQ-Test
  owner: Justin-MQ-Test
  parentdir: .
  protocol: https
  repo: multi-tenancy-gitops-apps
  url: https://github.com/Justin-MQ-Test/multi-tenancy-gitops-apps.git
